//because windows sucks...

#ifndef THREADEDFUNCTIONQTSO_CROSSPLATFORMMACROS_HPP
#define THREADEDFUNCTIONQTSO_CROSSPLATFORMMACROS_HPP

#include <QtCore/QtGlobal>

//remember to define this variable in the .pro file
#if defined(THREADEDFUNCTIONQTSO_LIB)
#  define EXPIMP_THREADEDFUNCTIONQTSO Q_DECL_EXPORT
#else
#  define EXPIMP_THREADEDFUNCTIONQTSO Q_DECL_IMPORT
#endif

#endif // THREADEDFUNCTIONQTSO_CROSSPLATFORMMACROS_HPP
